[DVI-D-1]
path = "/home/bcb/nixos-flake/wallpapers/Shiomiya_Shiori_Holding_Shy_C_Programming_language_wp_gruvbox.png"

[HDMI-A-1]
path = "/home/bcb/nixos-flake/wallpapers/anime_book_computer_grevbox_neofetch_vim.png"

[DP-1]
path = "/home/bcb/nixos-flake/wallpapers/i_am_root.png"
