# just --list
default:
    @just --list --unsorted

# sound controls
sound:
    pavucontrol

# bluetooth management
bluetooth:
    blueman-manager

# wifi management
wifi:
    nmtui

# ex 10s 7m
countdown TIME:
    termdown {{TIME}} --font univers
