# just --list
default:
    @just --list --unsorted

# sound controls
sound:
    myxer

# bluetooth management
bluetooth:
    bzmenu --launcher walker

# wifi management
wifi:
    nmtui

# ex 10s 7m
countdown TIME:
    termdown {{TIME}} --font univers
